- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance # Name of the task
      ec2: # Name of the command
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-d9124294
        assign_public_ip: 'yes'
        wait: 'yes'
        count: 2
        aws_access_key: '{{access_key}}'
        aws_secret_key: '{{secret_key}}'
        security_token: '{{session_token}}'
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched # Add all instances to the group name called LAUNCHED
      with_items: '{{ec2.instances}}' # For loop iterating over EC2 instances
     
    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Docker
      apt: 
        name: docker.io
        state: present
        update_cache: yes
      become: yes # Become sudo

    - service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Get project file from GIT repository
      git:
        repo: 'https://github.com/vfalada/4IT572_docker.git'
        dest: ./app # Create new foled app in root

    - name: Build docker image with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes

    - name: Run docker image with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45 # in seconds
      poll: 10 # in seconds
      become: yes
    - wait_for:
        port: 80
